# Mod basic information
mod_id = ElementalCraft-Reactions
mod_name = ElementalCraft: Reactions
mod_version = 1.7.6
mod_authors = xulai
mod_description = ElementalCraft: Reactions adds unique elemental reactions (fire, frost, thunder, nature) to Minecraft combat, inspired by Divinity: Original Sin 2 and Baldur's Gate 3.
mod_license = All Rights Reserved

# Minecraft and Forge versions
minecraft_version = 1.20.1
forge_version = 47.4.0
minecraft_version_range = [1.20.1,1.21)
forge_version_range = [47.4.0,)
loader_version_range = [4,)

# Mapping channel
mapping_channel = official
mapping_version = 1.20.1

mod_group_id = com.xulai.elementalcraft

systemProp.net.minecraftforge.gradle.check.certs=false